### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [tkrajina/10000sentences#1]
Would you consider publishing the `.apk` file here at Github, for folks without Playstore? This could be done easily via the Github release system (see [Creating Releases](https://help.github.com/articles/creating-releases/) in the Github help). If you do so, I can also offer to include your app with my [F-Droid compatible repo](https://android.izzysoft.de/repo), to make it even easier to get (and keep it updated) for those people. Thanks in advance!

**Comment by tkrajina** [comment]
Sure!

Just a question, I need to upload the same signed file I use for Google Play or is there any specific build configuration I should use?

**Comment by IzzySoft** [comment]
You can use the same. The quite strong rules of the "official F-Droid repo" concerning "unfree components" are not applied to mine.

**Comment by IzzySoft** [comment]
Hm, I see a release today – but no APK attached? Forgot it? :see_no_evil:

**Comment by tkrajina** [comment]
Don't worry ;) It's still in beta on google play. I wanted to be sure it works before publishing it in production there and then I'll create a release here (probably tomorrow).

**Comment by IzzySoft** [comment]
Thanks for your prompt reply! I stand by then and wait for your next update here :innocent:

**Comment by tkrajina** [comment]
Done, hope it's OK.

**Comment by IzzySoft** [comment]
Thanks a lot! Find it [here](https://apt.izzysoft.de/fdroid/index/apk/info.puzz.a10000sentences) now. Updates usually within 24h of your creating a new tag and attaching an APK to it :smiley_cat:
