### ISSUE TITLE
Seems to be missing on Google Play store

### ISSUE THREAD

**Issue by Whodathinkit** [tkrajina/10000sentences#17]
Similarly named apps, but some have adverts.  The URL referenced here does not work.  I hope you can republish on Play store and update URL.  Superb app.

**Comment by tkrajina** [comment]
Hey, yes, it's missing because I forgot to set the "target audience information" for the app. 

I did it now and I guess we have to wait for Google's confirmation that the app is "safe for use". Not sure how long this will take.

**Comment by Whodathinkit** [comment]
Thanks.  I'm recommending it to others at the moment.  Any chance of including the Cebuano change as well?
