### ISSUE TITLE
Support other translation apps

### ISSUE THREAD

**Issue by licaon-kter** [tkrajina/10000sentences#2]
Like [Yandex](https://play.google.com/store/apps/details?id=ru.yandex.translate) or [Translator](https://play.google.com/store/apps/details?id=com.microsoft.translator) or other, via some sort of menu maybe eg. `Default translator app`

Other idea: https://android-developers.googleblog.com/2015/10/in-app-translations-in-android.html

**Comment by tkrajina** [comment]
Yes, I agree Yandex and Translator could be a nice addition. Maybe I'll do it when I find some free time (unfortunately that's not very common nowadays).

Your other idea is already implemented :) In the most recent release (launched yesterday) I changed the sentence to be selectable. You can select one or more words and then you get the contextual menu which should also contain "Translate". If it don't, you can enable "tap to translate" in google translate, and then in 10,000 sentences, after selecting the tex -- select "Copy". A Google translation indicator should appear in the upper  right corner. If you have any problems with that, let me know.

**Comment by licaon-kter** [comment]
Indeed the second option works ok, I was sure I tested that but I missed it.

**Comment by licaon-kter** [comment]
Please open this as the main point still stands, pressing the `translate` button yields `no translation app available` although one might have Yandex and/or Translator installed.
