### ISSUE TITLE
I have a good idea

### ISSUE THREAD

**Issue by Pantyhose-X** [tkrajina/10000sentences#21]
Hello  I have a good idea you can develop a "listen"keyboard tool, The mother tongue is not English. Need to learn English, the market is very large

TTS+keyboard
* Text-to-Speech Always speak typed keys Speak phonetic letters Phonetic letters are spoken when long pressing on keyboard keys and navigating by character.
* Applied to language learner. Language worker's
* Applied to language learning. Pronunciation correction

* example，
https://play.google.com/store/apps/details?id=com.google.android.marvin.talkback&hl=en_IN&gl=US

https://user-images.githubusercontent.com/42504385/132130706-a1a8ec10-416a-4711-b5d3-c91086e9710f.mp4

https://www.youtube.com/watch?v=YPBn6D6pf78&t=207s

https://user-images.githubusercontent.com/42504385/127757873-c3c076d3-ce73-40b1-8f57-423459fc0c2f.MP4

* They don't have to close read the screen function. This is unfavorable to the learning language.
* l only want to talk when you press keys on the
keyboard, not to read the screen

# Additional context
[Mozilla's Text-to-Speech](https://github.com/mozilla/TTS)  
[coqui-ai TTS](https://github.com/coqui-ai/TTS) 
[Google Text-to-Speech apk](https://play.google.com/store/apps/details?id=com.google.android.tts&hl=en_US&gl=US)

**Comment by tkrajina** [comment]
Yes, I agree. It's an interesting idea. But it would be a completely different project and I don't have the time for that at the moment :(
