### ISSUE TITLE
Releases on Github

### ISSUE THREAD

**Issue by licaon-kter** [tkrajina/10000sentences#4]
...are rather behind Google Play store.

No release tags, no APKs.

**Comment by JonnyTech** [comment]
@tkrajina please build an updated apk for us non play store users and those that get it from the repo provided by @IzzySoft

**Comment by IzzySoft** [comment]
@tkrajina No APK from you, no update via my repo. I cannot build it myself, so we all depend on you. Will you have pity with us? :pray:

**Comment by IzzySoft** [comment]
If there are no APKs available, I will have to remove the app from my repo. I don't want to serve outdated versions. So please, could you attache the corresponding `.apk` to the last release, @tkrajina ?

**Comment by IzzySoft** [comment]
Sorry to tell you: but as there has been no response for more than 2 months, I've removed the app from my repo for above mentioned reasons. If you decide to attach `.apk` files again to your releases, please let me know so I can re-list your app.

**Comment by licaon-kter** [comment]
So...no?

**Comment by IzzySoft** [comment]
Obviously. @tkrajina isn't very communicative in this context – but closing the issue without a comment to me says very clearly "not interested". And I'm not interested in "chasing", which is why I dropped it.

**Comment by IzzySoft** [comment]
Thanks for chiming in, @tkrajina! So while you again provide the APK now, do I understand correctly you want me to keep it out of my repo? What good would that do – while at the same time having it on Google Play? Compared to the users from there, those added via my repo are just few – mostly those who cannot or do not want to use Playstore. For them it makes it easier to install the app and keep it up to date. So you'd rather avoid issues being opened for old versions they found "somewhere".

Of course I'll respect your decision – and those do not re-add it now right away. But please re-evaluate the pros and cons. Then let me know if you decided I should serve it again. Easy to re-establish, as I've kept the configuration.

**Comment by tkrajina** [comment]
No, sorry if I wasn't clear. I wanted to say that I respect and understand your decision to remove the app from your repo. If you want to keep it, I'm absolutely OK with it.

**Comment by IzzySoft** [comment]
Thanks for clarification, @tkrajina – added it back! Main purpose for removal was I couldn't obtain the latest version anymore, and I don't want to serve only the old ones when on a different place (here: Playstore) newer versions are available, so one day mine would be completely outdated.

Will continue serving it until you tell me not to – or you again no longer attach it and don't respond for a long time :wink:

**Comment by IzzySoft** [comment]
Just a gentle question: do you really need 3 analytics frameworks in a single app? Too many trackers scare privacy-aware users away (e.g. I wouldn't install it as long as they are there). Maybe you could kick out Firebase, Firebase Analytics and Google Tag manager? and ideally replace Google Analytics with something more privacy-friendly, like ACRA or at least Matomo? Thanks in advance, @tkrajina!

**Comment by tkrajina** [comment]
@IzzySoft Frankly, I never even look at those stats. In fact, some of those probably come as transitional dependencies to google analytics (I don't use firebase). 

That said, at the moment I really don't have the time to do that. So, if somebody is willing to try it -- a PR is welcome.

**Comment by IzzySoft** [comment]
Thanks, @tkrajina – I've moved that to its own issue then, explicitly asking for PRs.
