### ISSUE TITLE
Help Wanted: Tracker removal

### ISSUE THREAD

**Issue by IzzySoft** [tkrajina/10000sentences#9]
As stated [here](https://github.com/tkrajina/10000sentences/issues/4#issuecomment-468735047), trackers like Google Analytics, Firebase Analytics (incl. Firebase itself) and Google Tag Manager are no longer needed and should be removed. Since @tkrajina currently lacks time to scrape that out, Pull Requests are welcome!

**Comment by tkrajina** [comment]
I think https://github.com/tkrajina/10000sentences/releases/tag/0.3.3 should have this problem fixed. But I'll spend a few more days testing it before I release a version and upload the apk.

This is the new dependencies tree:

```
releaseAnnotationProcessorClasspath - Resolved configuration for annotation-processor for variant: release
+--- org.projectlombok:lombok:1.16.20
+--- com.google.dagger:dagger-compiler:2.8
|    +--- com.google.dagger:dagger:2.8
|    |    \--- javax.inject:javax.inject:1
|    +--- com.google.dagger:dagger-producers:2.8
|    |    +--- com.google.dagger:dagger:2.8 (*)
|    |    \--- com.google.guava:guava:20.0-rc1 -> 23.0
|    |         +--- com.google.code.findbugs:jsr305:1.3.9
|    |         +--- com.google.errorprone:error_prone_annotations:2.0.18
|    |         +--- com.google.j2objc:j2objc-annotations:1.1
|    |         \--- org.codehaus.mojo:animal-sniffer-annotations:1.14
|    \--- com.google.guava:guava:20.0-rc1 -> 23.0 (*)
\--- androidx.databinding:databinding-compiler:3.2.1
     +--- androidx.databinding:databinding-compiler-common:3.2.1
     |    +--- androidx.databinding:databinding-common:3.2.1
     |    +--- com.android.databinding:baseLibrary:3.2.1
     |    +--- org.antlr:antlr4:4.5.3
     |    +--- commons-io:commons-io:2.4
     |    +--- com.googlecode.juniversalchardet:juniversalchardet:1.0.3
     |    +--- com.google.guava:guava:23.0 (*)
     |    +--- com.squareup:javapoet:1.8.0
     |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71
     |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.2.71
     |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.2.71
     |    |    |    \--- org.jetbrains:annotations:13.0
     |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.71
     |    |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.2.71 (*)
     |    +--- com.google.code.gson:gson:2.8.0
     |    +--- com.android.tools:annotations:26.2.1
     |    \--- com.android.tools.build.jetifier:jetifier-core:1.0.0-alpha10
     |         +--- com.google.code.gson:gson:2.8.0
     |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.2.20 -> 1.2.71 (*)
     +--- androidx.databinding:databinding-common:3.2.1
     +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71 (*)
     +--- commons-io:commons-io:2.4
     +--- commons-codec:commons-codec:1.9
     +--- org.antlr:antlr4:4.5.3
     \--- com.googlecode.juniversalchardet:juniversalchardet:1.0.3
```

**Comment by IzzySoft** [comment]
That graph looks good indeed! Let's see what my scanner says when the APK is available – but seeing that graph, I'm quite optimistic. Thanks a lot!

**Comment by tkrajina** [comment]
Here's the apk: https://github.com/tkrajina/10000sentences/releases/tag/0.3.3

**Comment by IzzySoft** [comment]
I just told my updater to check, and it found the new version. After the scanner completed its run it told me "no longer Tracking" right away. Checking the remains: That looks splendid! So I removed the other two (NonFreeDep and NonFreeNet) as well, taking effect with the next sync in about 7h.

Congrats and thanks! :tada:

If you now want to get your app into the official repo, I gladly assist with that – just let me know. Otherwise, I consider this issue solved :smiley:

**Comment by tkrajina** [comment]
@IzzySoft I'm not really sure what do you mean with "official repo", can you enlighten me? :)

**Comment by licaon-kter** [comment]
@tkrajina F-Droid official repo is the one on https://f-droid.org where packages are build from source

Izzy's repo holds only APKs....no building is done.

**Comment by IzzySoft** [comment]
That, and the official repo is much more prominent and has a higher trust level. So if possible, that's what to aim for. You just made it possible, so… :wink:

**Comment by tkrajina** [comment]
Hm, yes, I agree. It might be a good idea. I'll implement do it when I find a couple of hours to figure out how.

**Comment by IzzySoft** [comment]
@tkrajina just give me the go and I file an RFP for you. Takes a little load from your shoulders. With some luck, there are no issues and @licaon-kter will process it right away :smiley:

**Comment by tkrajina** [comment]
@IzzySoft Ah, OK, if it's that easy, of course. Thanks! When it's done, just let me know the public URL so that I can add it in the `README.md`.

**Comment by IzzySoft** [comment]
Ah well, someone was faster and [already opened an RFP](https://gitlab.com/fdroid/rfp/issues/768) about a year ago – which was not processed due to, ahem, trackers. Updated that with a complete metadata block, kicked out the "bad flags", and told the bot to scan again (I can do that as I'm one of the maintainers there – oops, late disclosure :rofl:)

So in a day we know more (the bot just runs once in 24h).
